---
- name: Adding key {{ elrepo_rpm_gpg_url }}
  become: true
  become_user: root
  ansible.builtin.rpm_key:
    key: '{{ elrepo_rpm_gpg_url }}'
    state: present

- name: Installing {{ elrepo_rpm_url }}
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ elrepo_rpm_url }}'
    state: present
