---
- name: adding key {{ elrepo_rpm_gpg_url }}
  become: true
  become_user: root
  rpm_key:
    key: '{{ elrepo_rpm_gpg_url }}'
    state: present

- name: installing {{ elrepo_rpm_url }}
  become: true
  become_user: root
  package:
    name: '{{ elrepo_rpm_url }}'
    state: present
